[package]
name = "xgpu-server"
version = "0.1.0"
edition = "2024"

[dependencies]
xgpu-common = { path = "../common" }
cudax = { path = "../cudax" }
tracing = "0.1.41"
tracing-subscriber = "0.3"
indexmap = "2.11.4"
lazy_static = "1.4.0"